### ISSUE TITLE
Refresh Interval Off

### ISSUE THREAD

**Issue by benawad** [vnovick/graphql-jwt-tutorial#1]
Should be 14 minutes, not 1 minute https://github.com/vnovick/graphql-jwt-tutorial/blob/master/nextjsapp/utils/auth.js#L73

**Comment by vnovick** [comment]
Switched it to 15 minutes, but the check will still be every minute. It's just auth will happen every 14. 
BTW you might wanna check the new api I pushed. Now I have two versions. One is at backend folder and other one is in nextjsapp/api
